# Generated by Django 3.1.5 on 2021-01-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_auto_20210112_1730'),
        ('servicestations', '0002_auto_20210113_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestation',
            name='queue',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='queues.queue'),
        ),
    ]
