# Generated by Django 3.1.5 on 2021-01-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_auto_20210112_1730'),
        ('servicestations', '0003_servicestation_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestation',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='queues.queue'),
        ),
    ]
