# Generated by Django 3.1.5 on 2021-01-25 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicestations', '0004_auto_20210123_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestation',
            name='provider',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
