# Generated by Django 3.1.5 on 2021-01-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_auto_20210112_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='users',
        ),
    ]
