# Generated by Django 3.1.5 on 2021-01-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_remove_queue_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_queue',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_queue',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
