# Generated by Django 3.1.5 on 2021-01-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_auto_20210125_1755'),
        ('queues', '0004_auto_20210125_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_queue',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.process_user'),
        ),
    ]
